import {
  CanonicalPersonProfile,
  ConflictQueueItem,
  PersonMentionRecord,
  ResolutionMetric,
} from './types';

export const resolutionMetrics: ResolutionMetric[] = [
  {
    label: 'Resolvable mentions',
    value: '184',
    tone: 'primary',
    detail: 'Mentions with at least one viable identity candidate',
  },
  {
    label: 'Low-confidence cases',
    value: '27',
    tone: 'warning',
    detail: 'Below 0.60 confidence and should stay analyst-visible',
  },
  {
    label: 'Duplicate profiles',
    value: '11',
    tone: 'danger',
    detail: 'Likely same person represented by parallel aliases',
  },
  {
    label: 'Resolved this shift',
    value: '92%',
    tone: 'success',
    detail: 'Analyst-confirmed or evidence-safe automated resolutions',
  },
];

export const canonicalProfiles: CanonicalPersonProfile[] = [
  {
    id: 'PID-001',
    canonicalName: 'Alexander Petrovich Volkov',
    aliases: ['Александр Волков', 'Aleksandr Volkov', 'A. P. Volkov', 'Alex Volkov'],
    organizations: ['Gazprom Neft', 'Vega Maritime Holdings'],
    roles: ['Strategic adviser', 'Board liaison'],
    locations: ['Moscow', 'Limassol', 'Dubai Free Zone'],
    linkedDocuments: [
      { id: 'DOC-401', title: 'Shipping corridor coordination memo', date: '2026-03-04', mentionCount: 5 },
      { id: 'DOC-417', title: 'Cyprus registry extract', date: '2026-02-11', mentionCount: 3 },
    ],
    timeline: [
      { date: '2026-02-11', event: 'Appears as beneficial owner in Cyprus registry extract', documentTitle: 'Cyprus registry extract', confidence: 0.91 },
      { date: '2026-03-04', event: 'Referenced in shipping corridor coordination memo with Dubai routing context', documentTitle: 'Shipping corridor coordination memo', confidence: 0.89 },
      { date: '2026-03-18', event: 'Surname-only mention tied to prior employer and travel evidence', documentTitle: 'Port access audit', confidence: 0.76 },
    ],
    evidence: [
      {
        id: 'EV-001',
        documentId: 'DOC-401',
        page: 3,
        source: 'Shipping corridor coordination memo',
        snippet: 'Aleksandr Volkov approved the revised vessel rotation after Dubai customs clearance was delayed.',
        date: '2026-03-04',
        language: 'English',
      },
      {
        id: 'EV-002',
        documentId: 'DOC-417',
        page: 1,
        source: 'Cyprus registry extract',
        snippet: 'Beneficiary owner: Александр Волков (Alexander Petrovich Volkov), Vega Maritime Holdings.',
        date: '2026-02-11',
        language: 'Russian',
      },
    ],
    confidenceSummary: 0.93,
    contradictions: [],
    facts: [
      { label: 'Organization', value: 'Gazprom Neft', confidence: 0.88, evidenceIds: ['EV-001'] },
      { label: 'Organization', value: 'Vega Maritime Holdings', confidence: 0.93, evidenceIds: ['EV-002'] },
      { label: 'Location', value: 'Dubai Free Zone', confidence: 0.81, evidenceIds: ['EV-001'] },
    ],
    unresolvedAliases: [],
  },
  {
    id: 'PID-002',
    canonicalName: 'Yousef Haddad',
    aliases: ['يوسف حداد', 'יוסף חדאד', 'Y. Haddad', 'Yousef H.'],
    organizations: ['Meridian Relief Network', 'North Gate Logistics'],
    roles: ['Field coordinator', 'Procurement intermediary'],
    locations: ['Amman', 'Jerusalem', 'Ramallah'],
    linkedDocuments: [
      { id: 'DOC-422', title: 'Border meeting notes', date: '2026-03-19', mentionCount: 4 },
      { id: 'DOC-430', title: 'Procurement contact ledger', date: '2026-04-01', mentionCount: 6 },
    ],
    timeline: [
      { date: '2026-03-19', event: 'Hebrew mention tied to field logistics near Jerusalem', documentTitle: 'Border meeting notes', confidence: 0.73 },
      { date: '2026-04-01', event: 'Arabic-script email signature linked to Meridian Relief Network', documentTitle: 'Procurement contact ledger', confidence: 0.78 },
    ],
    evidence: [
      {
        id: 'EV-010',
        documentId: 'DOC-422',
        page: 2,
        source: 'Border meeting notes',
        snippet: 'יוסף חדאד coordinated the truck manifest before the team crossed toward Jerusalem.',
        date: '2026-03-19',
        language: 'Hebrew',
      },
      {
        id: 'EV-011',
        documentId: 'DOC-430',
        page: 5,
        source: 'Procurement contact ledger',
        snippet: 'Signed: يوسف حداد, Meridian Relief Network procurement desk.',
        date: '2026-04-01',
        language: 'Arabic',
      },
    ],
    confidenceSummary: 0.79,
    contradictions: ['Organization evidence spans both humanitarian and logistics contexts; keep under analyst watch.'],
    facts: [
      { label: 'Role', value: 'Field coordinator', confidence: 0.71, evidenceIds: ['EV-010'] },
      { label: 'Organization', value: 'Meridian Relief Network', confidence: 0.78, evidenceIds: ['EV-011'] },
    ],
    unresolvedAliases: ['Yusuf Haddad'],
  },
  {
    id: 'PID-003',
    canonicalName: 'Li Wei',
    aliases: ['李伟', 'Li Wei', 'L. Wei'],
    organizations: ['Eastern Grid Systems'],
    roles: ['Regional director'],
    locations: ['Shenzhen', 'Guangzhou'],
    linkedDocuments: [{ id: 'DOC-455', title: 'Grid modernization brief', date: '2026-04-02', mentionCount: 2 }],
    timeline: [
      { date: '2026-04-02', event: 'Mentioned as Regional director in grid modernization brief', documentTitle: 'Grid modernization brief', confidence: 0.62 },
    ],
    evidence: [
      {
        id: 'EV-020',
        documentId: 'DOC-455',
        page: 7,
        source: 'Grid modernization brief',
        snippet: 'Li Wei reviewed the substation migration schedule for Shenzhen operations.',
        date: '2026-04-02',
        language: 'English',
      },
    ],
    confidenceSummary: 0.58,
    contradictions: ['Name remains highly ambiguous across open-source holdings; no safe merge outside current case context.'],
    facts: [
      { label: 'Organization', value: 'Eastern Grid Systems', confidence: 0.61, evidenceIds: ['EV-020'] },
    ],
    unresolvedAliases: ['Li Wei (State Grid candidate)', 'Li Wei (Shenzhen customs candidate)'],
  },
  {
    id: 'PID-004',
    canonicalName: 'Mohammed bin Rashid Al-Maktoum (associate)',
    aliases: ['محمد بن راشد', 'bin Rashid', 'M. bin Rashid'],
    organizations: ['Dubai Investment Group'],
    roles: ['Advisor'],
    locations: ['Dubai'],
    linkedDocuments: [{ id: 'DOC-462', title: 'Free zone access log', date: '2026-04-05', mentionCount: 2 }],
    timeline: [
      { date: '2026-04-05', event: 'Possible match in free zone access log, unresolved due to patronymic ambiguity', documentTitle: 'Free zone access log', confidence: 0.44 },
    ],
    evidence: [
      {
        id: 'EV-030',
        documentId: 'DOC-462',
        page: 1,
        source: 'Free zone access log',
        snippet: 'Contact established via bin Rashid near warehouse corridor D-14 in the Dubai free zone.',
        date: '2026-04-05',
        language: 'English',
      },
    ],
    confidenceSummary: 0.44,
    contradictions: ['Do not auto-merge: multiple public figures and private associates match this patronymic.'],
    facts: [],
    unresolvedAliases: ['Rashid bin Mohammed Al-Nahyan'],
  },
];

export const personMentions: PersonMentionRecord[] = [
  {
    id: 'M-001',
    documentId: 'DOC-401',
    documentTitle: 'Shipping corridor coordination memo',
    page: 3,
    rawMention: 'Александр Волков',
    normalizedMention: 'Alexander Volkov',
    confidence: 0.93,
    language: 'Russian',
    sourceSnippet: 'Вчера Александр Волков подтвердил судовой слот после проверки груза в дубайской зоне свободной торговли.',
    suggestedIdentityId: 'PID-001',
    status: 'resolved',
    surroundingEntities: ['Gazprom Neft', 'Dubai Free Zone', 'Vega Maritime Holdings'],
    alternatives: [
      {
        id: 'PID-001',
        canonicalName: 'Alexander Petrovich Volkov',
        score: 0.95,
        scoreBreakdown: {
          aliasSimilarity: 0.98,
          transliterationSimilarity: 0.96,
          organizationOverlap: 0.88,
          locationOverlap: 0.84,
          roleTitleOverlap: 0.67,
          timelineOverlap: 0.81,
          evidenceCount: 12,
          explanation: 'Cyrillic alias, Cyprus registry alias, and Dubai routing context align strongly with the existing profile.',
        },
        matchReasons: ['Exact alias family', 'Employer overlap', 'Travel pattern overlap'],
        organizations: ['Gazprom Neft', 'Vega Maritime Holdings'],
        roles: ['Strategic adviser'],
        locations: ['Moscow', 'Dubai Free Zone'],
      },
    ],
  },
  {
    id: 'M-002',
    documentId: 'DOC-430',
    documentTitle: 'Procurement contact ledger',
    page: 5,
    rawMention: 'يوسف حداد',
    normalizedMention: 'Yousef Haddad',
    confidence: 0.78,
    language: 'Arabic',
    sourceSnippet: 'وقع يوسف حداد على نموذج الشحن بصفته نقطة اتصال للمشتريات في Meridian Relief Network.',
    suggestedIdentityId: 'PID-002',
    status: 'uncertain',
    surroundingEntities: ['Meridian Relief Network', 'Amman', 'shipment form'],
    alternatives: [
      {
        id: 'PID-002',
        canonicalName: 'Yousef Haddad',
        score: 0.79,
        scoreBreakdown: {
          aliasSimilarity: 0.87,
          transliterationSimilarity: 0.92,
          organizationOverlap: 0.84,
          locationOverlap: 0.58,
          roleTitleOverlap: 0.63,
          timelineOverlap: 0.61,
          evidenceCount: 7,
          explanation: 'Arabic signature and procurement context align, but organization evidence spans multiple operational fronts.',
        },
        matchReasons: ['Arabic-script alias', 'Procurement role overlap'],
        conflictReasons: ['Parallel logistics affiliation not fully reconciled'],
        organizations: ['Meridian Relief Network', 'North Gate Logistics'],
        roles: ['Field coordinator', 'Procurement intermediary'],
        locations: ['Amman', 'Ramallah'],
      },
    ],
  },
  {
    id: 'M-003',
    documentId: 'DOC-422',
    documentTitle: 'Border meeting notes',
    page: 2,
    rawMention: 'יוסף חדאד',
    normalizedMention: 'Yosef Haddad',
    confidence: 0.66,
    language: 'Hebrew',
    sourceSnippet: 'יוסף חדאד תיאם את חלון המעבר לפני שהמשאית נכנסה לאזור ירושלים.',
    suggestedIdentityId: 'PID-002',
    status: 'uncertain',
    surroundingEntities: ['Jerusalem', 'truck manifest', 'North Gate Logistics'],
    alternatives: [
      {
        id: 'PID-002',
        canonicalName: 'Yousef Haddad',
        score: 0.73,
        scoreBreakdown: {
          aliasSimilarity: 0.81,
          transliterationSimilarity: 0.88,
          organizationOverlap: 0.46,
          locationOverlap: 0.77,
          roleTitleOverlap: 0.52,
          timelineOverlap: 0.59,
          evidenceCount: 5,
          explanation: 'Hebrew spelling variant matches known alias family and regional travel corridor, but employer context is only partial.',
        },
        matchReasons: ['Hebrew alias variant', 'Location overlap'],
        organizations: ['North Gate Logistics'],
        roles: ['Field coordinator'],
        locations: ['Jerusalem', 'Ramallah'],
      },
      {
        id: 'PID-005',
        canonicalName: 'Yosef Haddad (customs broker)',
        score: 0.54,
        scoreBreakdown: {
          aliasSimilarity: 0.79,
          transliterationSimilarity: 0.82,
          organizationOverlap: 0.2,
          locationOverlap: 0.48,
          roleTitleOverlap: 0.6,
          timelineOverlap: 0.29,
          evidenceCount: 2,
          explanation: 'Possible alternate broker identity with matching Hebrew spelling but weak document context.',
        },
        matchReasons: ['Spelling overlap'],
        conflictReasons: ['Insufficient employer overlap'],
        organizations: ['Jordan Gate Brokerage'],
        roles: ['Customs broker'],
        locations: ['Jerusalem'],
      },
    ],
  },
  {
    id: 'M-004',
    documentId: 'DOC-462',
    documentTitle: 'Free zone access log',
    page: 1,
    rawMention: 'bin Rashid',
    normalizedMention: 'Mohammed bin Rashid',
    confidence: 0.45,
    language: 'Arabic transliteration',
    sourceSnippet: 'Contact was established via bin Rashid near corridor D-14 in the Dubai free zone.',
    suggestedIdentityId: 'PID-004',
    status: 'conflict',
    surroundingEntities: ['Dubai', 'warehouse corridor D-14', 'free zone badge office'],
    alternatives: [
      {
        id: 'PID-004',
        canonicalName: 'Mohammed bin Rashid Al-Maktoum (associate)',
        score: 0.48,
        scoreBreakdown: {
          aliasSimilarity: 0.82,
          transliterationSimilarity: 0.91,
          organizationOverlap: 0.31,
          locationOverlap: 0.94,
          roleTitleOverlap: 0.18,
          timelineOverlap: 0.42,
          evidenceCount: 2,
          explanation: 'Location overlap is strong, but the patronymic is too generic to force a merge without stronger employer evidence.',
        },
        matchReasons: ['Dubai location overlap'],
        conflictReasons: ['Generic patronymic', 'Public figure collision risk'],
        organizations: ['Dubai Investment Group'],
        roles: ['Advisor'],
        locations: ['Dubai'],
      },
      {
        id: 'PID-006',
        canonicalName: 'Rashid bin Mohammed Al-Nahyan',
        score: 0.43,
        scoreBreakdown: {
          aliasSimilarity: 0.79,
          transliterationSimilarity: 0.86,
          organizationOverlap: 0.11,
          locationOverlap: 0.79,
          roleTitleOverlap: 0.12,
          timelineOverlap: 0.36,
          evidenceCount: 1,
          explanation: 'Region fit is plausible, but the name order and organizational evidence remain weak.',
        },
        matchReasons: ['Regional fit'],
        conflictReasons: ['Name inversion', 'No organization overlap'],
        organizations: ['Private office'],
        roles: ['Unknown'],
        locations: ['Abu Dhabi', 'Dubai'],
      },
    ],
  },
  {
    id: 'M-005',
    documentId: 'DOC-455',
    documentTitle: 'Grid modernization brief',
    page: 7,
    rawMention: '李伟',
    normalizedMention: 'Li Wei',
    confidence: 0.22,
    language: 'Chinese',
    sourceSnippet: '项目由李伟负责审阅，但文件没有进一步提供所属机构或职务。',
    suggestedIdentityId: 'PID-003',
    status: 'unresolved',
    surroundingEntities: ['substation migration', 'Shenzhen', 'review cycle'],
    alternatives: [
      {
        id: 'PID-003',
        canonicalName: 'Li Wei',
        score: 0.28,
        scoreBreakdown: {
          aliasSimilarity: 1,
          transliterationSimilarity: 1,
          organizationOverlap: 0.08,
          locationOverlap: 0.16,
          roleTitleOverlap: 0.05,
          timelineOverlap: 0.12,
          evidenceCount: 1,
          explanation: 'String match only. Context is too thin to resolve safely because Li Wei is a highly common name.',
        },
        matchReasons: ['Exact script match'],
        conflictReasons: ['Name frequency too high', 'Sparse organizational evidence'],
        organizations: ['Eastern Grid Systems'],
        roles: ['Regional director'],
        locations: ['Shenzhen'],
      },
    ],
  },
  {
    id: 'M-006',
    documentId: 'DOC-433',
    documentTitle: 'Procurement chain email',
    page: 4,
    rawMention: 'Alex Volkov',
    normalizedMention: 'Alexander Volkov',
    confidence: 0.81,
    language: 'English',
    sourceSnippet: 'Alex Volkov asked the broker to keep Vega Maritime off the revised invoice trail.',
    suggestedIdentityId: 'PID-001',
    status: 'resolved',
    surroundingEntities: ['Vega Maritime', 'broker', 'invoice trail'],
    alternatives: [
      {
        id: 'PID-001',
        canonicalName: 'Alexander Petrovich Volkov',
        score: 0.9,
        scoreBreakdown: {
          aliasSimilarity: 0.94,
          transliterationSimilarity: 0.73,
          organizationOverlap: 0.89,
          locationOverlap: 0.52,
          roleTitleOverlap: 0.61,
          timelineOverlap: 0.72,
          evidenceCount: 9,
          explanation: 'Nickname alias plus known maritime entity produces a strong, evidence-rich resolution.',
        },
        matchReasons: ['Nickname alias', 'Organization overlap'],
        organizations: ['Vega Maritime Holdings'],
        roles: ['Strategic adviser'],
        locations: ['Limassol', 'Dubai'],
      },
    ],
  },
];

export const documentReviewSnippets = [
  {
    id: 'DOC-401',
    title: 'Shipping corridor coordination memo',
    date: '2026-03-04',
    excerpt:
      'Вчера Александр Волков подтвердил судовой слот после проверки груза в дубайской зоне свободной торговли. Alex Volkov later asked the broker to keep Vega Maritime off the revised invoice trail.',
    mentionIds: ['M-001', 'M-006'],
  },
  {
    id: 'DOC-430',
    title: 'Procurement contact ledger',
    date: '2026-04-01',
    excerpt:
      'وقع يوسف حداد على نموذج الشحن بصفته نقطة اتصال للمشتريات في Meridian Relief Network. Contact was later routed through a North Gate Logistics intermediary.',
    mentionIds: ['M-002'],
  },
  {
    id: 'DOC-462',
    title: 'Free zone access log',
    date: '2026-04-05',
    excerpt:
      'Contact was established via bin Rashid near corridor D-14 in the Dubai free zone. Badge issuance record omitted the full patronymic and employer.',
    mentionIds: ['M-004'],
  },
];

export const conflictQueue: ConflictQueueItem[] = [
  {
    mentionId: 'M-004',
    canonicalHint: 'Mohammed bin Rashid',
    reason: 'High-profile patronymic collision with multiple plausible identities in the same city.',
    severity: 'critical',
  },
  {
    mentionId: 'M-005',
    canonicalHint: 'Li Wei',
    reason: 'Exact script match but no safe organization evidence for resolution.',
    severity: 'high',
  },
  {
    mentionId: 'M-003',
    canonicalHint: 'Yousef Haddad',
    reason: 'Hebrew alias likely belongs to the same operator, but logistics affiliation remains split.',
    severity: 'medium',
  },
];
